name: flutter_chatter_hub
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.5.3







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  emoji_picker_flutter: ^4.3.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  go_router: ^17.0.0
  get_it: ^9.2.0
  shared_preferences: ^2.5.3
  image_picker: ^1.2.1
  provider: ^6.1.5+1
  uuid: ^4.5.2
  firebase_storage: ^12.4.10
  cloud_firestore: ^5.6.12
  firebase_app_check: ^0.3.2+10
  video_player: ^2.10.1
  zego_uikit_prebuilt_call: ^4.17.13
  zego_uikit_signaling_plugin: ^2.8.20
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^4.0.0





flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - assets/images/
     
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
